### ISSUE TITLE
[功能请求] 净化直播

### ISSUE THREAD

**Issue by weitia** [lliioollcn/PPHelper#1]
![Screenshot_20221001-110113.jpg](https://user-images.githubusercontent.com/100296027/193383914-f0e745d9-c351-4d02-91ad-0d54fe0be27d.jpg)

**Comment by lliioollcn** [comment]
开启语音房去除功能后虽然主页能刷到但是点不开，等有时间修

**Comment by lliioollcn** [comment]
已完成
